### ISSUE TITLE
MISC: dprime()'s slightly misleading documentation

### ISSUE THREAD

**Issue by hahong** [npinto/bangmetric#6]
In lines 24--25 of dprime.py (https://github.com/npinto/bangmetric/blob/master/bangmetric/dprime.py), the description of `y_pred` that "interpreted as strictly positive or not (i.e. converted to binary)" is slightly misleading.   I would just simply remove that part.

-Ha

**Comment by npinto** [comment]
Unfortunately, we can't remove that part as we need to be clear about how the values are interpreted. If you have another way to explain the same thing, please let us know.

cc: @poilvert

**Comment by hahong** [comment]
Do you have rules about documentation?  It would be good for me to follow that too.

Meanwhile, I guess I'm not still getting your point completely.  After all, `y_pred` is not converted to binaries... am I missing something?  Or is that referring binary classification?

-Ha

**Comment by npinto** [comment]
No I think you are right, `y_true` are binarized, not `y_pred`. I'll fix this. Thanks for the report!

**Comment by npinto** [comment]
Fixed in 892fe96.
